Задание №1 и немного №2
htmlacademy-htmlcss/1802169-sedona-31 pull request #3
Opened 2021-05-23 16:48 UTC by Longstocky

2021-05-25 15:54 UTC, ant1quar requested changes

2021-05-25 15:54 UTC, ant1quar commented on index.html
> +            <p>Рекомендуем пожить в настоящем мотеле,
А где тут иконки?

2021-05-25 15:54 UTC, ant1quar commented on index.html
> +        </form>
Форму после нужно будет подправить.

2021-05-26 17:57 UTC, Longstocky commented on index.html
> +    <main>
Добавила

2021-05-26 17:58 UTC, Longstocky commented on index.html
> +            <p>Рекомендуем пожить в настоящем мотеле,
Добавила класс, чтобы в будущем добавить иконки в css

2021-05-26 17:59 UTC, Longstocky commented on index.html
> +        </form>
Можно подробнее, что конкретно подправить и почему.

2021-05-26 18:00 UTC, Longstocky commented on catalog.html
> +      Телефон: +7 800 555-86-28</p>
добавила

2021-05-28 11:50 UTC, ant1quar commented on index.html
> +        </li>
поддержка стилизации номеров у тега ol не сильная. лучше вынести нумерацию в отдельный тег

2021-05-28 11:52 UTC, ant1quar commented on index.html
> +      </section>
В такой структуре будет сложно сверстать так, чтобы блок с бургерами был между блоком с причинами. нужно переделать и все расположить в одном однообразном списке. часть с нумерацией, а часть - нет

2021-05-28 11:57 UTC, ant1quar commented on index.html
> +        </form>
На данном этапе нужно вынести каждый инпут в отдельный блок
`<p>` для этого не подходит. лучше `<fieldset>`
и каждая пара `input` `label` должна быть в совем `fieldset`

2021-05-28 12:00 UTC, ant1quar requested changes

2021-05-28 12:00 UTC, ant1quar commented on catalog.html
> +            </li>
нет верстки для звездочек и рейтинга

2021-05-30 19:38 UTC, Longstocky commented
Разметка второй страницы

2021-05-30 20:01 UTC, merged