Сетка на гридах для главной страницы
htmlacademy-htmlcss/1802169-sedona-31 pull request #7
Opened 2021-07-06 18:20 UTC by Longstocky

2021-07-07 01:29 UTC, ant1quar requested changes

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +    display: grid;
тут не нужен грид, у тебя внутри только один элемент.

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +    display: grid;
тут тоже грид не нужен. 
Нужно немного хитрее - меню нужно растянуть во всю ширину, а логотип расположить поверх

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +    margin: 0;
тут нужен display: flex

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +    grid-template-columns: 400px 400px 400px;
так короче
```suggestion
    grid-template-columns: repeat(3, 400px);
```

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +}
Молодец)

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +}
тут это не обязательно. 
По хорошему нужно завести всем элементам в списке общий класс. 
и ставить grid-column только некоторым. 
Кажется я писал в чате на эту тему

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
> +    grid-template-columns: 400px 400px 400px;
тут тоже repeat

2021-07-07 01:29 UTC, ant1quar commented on css/style.css
Тут что-то с комментами произошло

2021-07-07 01:29 UTC, ant1quar commented on index.html
> +                <div class="main_navigation_wrapper">
Сильно большая вложенность. main_navigation_wrapper лишний

2021-07-07 01:29 UTC, ant1quar commented on index.html
> +                        <a class="main_header_logo" href="index.html">
И без main_header_logo можно обойтись

2021-07-08 02:27 UTC, Longstocky commented on index.html
> +                        <a class="main_header_logo" href="index.html">
Ага, я подумала может его тоже стоит сделать элементом <li>.  Как и в сетке с features_wide мне долго не удавалось впихнуть контент в сетку. Пока я каждому элементу не задала отдельный <li>.
 <li> текст про седона-городок и <li> картинка. Но я так и не поняла насколько это корректно. Это строки 50-58 в index.html

2021-07-11 13:40 UTC, Longstocky commented on css/style.css
> +    margin: 0;
готово

2021-07-11 22:51 UTC, merged